AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FlaskCambio:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.app
      Runtime: python3.12
      CodeUri: .
      Timeout: 10
      MemorySize: 256
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
